var language = {
    tour: {
        welcome: "Welcome to the card game.",
        description: "Here you wil find misconceptions about Bitcoin.",
        startTour: "Start short tour",
        dontShowAgain: "Do not show this again"
    },
    menu: {
        cards: "Cards",
        about: "About",
        scores: "Scores",
        quiz: "Quiz"
    },
    expert1: "Eric Voskuil",
    expert1Description: "",
    expert1Logo: "",
    expert2: "Expert 2",
    expert2Description: "",
    expert2Logo: "",
    expert3: "Bitcoin Wiki",
    expert3Description: "This bitcoin misconception cleared up by the bitcoin wiki community: ",
    expert3Logo: "",
    misconception: "Misconception",
    showAllCards: "Show all cards",
    backToCards: "Back to cards",
    backToCardIntro: "Back",
    reply: "Reply",
    related: "Related",
    keywords: "Keywords",
    random: "Random",
    shortAnswer: "In Short",
    longAnswer: "Longer Answer",
    diagram: "Diagram",
    readMore: "Read More",
    readOn: "Read On",
    searchBarPlaceholderText: "Search",
    searchGoToCard: "▶ Go to card",
    everythingAbout: "Everything about",
    searchResultsCopyOption: "Search results",
    openFullCard: "Open full card",
    counterQuestions: "Counter Questions",
    analogy: "Analogy",
    flowerPower: "Flower Power",
    shareMessage: "You can now paste the link on Twitter, Facebook etc.",
    tweetStream: {
        message1: "<ul><li><h2>Find a tweet</h2></li><li><h2>Find a card</h2></li><li><h2>Reply with card</h2></li></ul>",
        message1a: "<ul><li><h2>Find a tweet</h2></li><li><h2>Find a card</h2></li><li><h2>Reply with card</h2></li></ul>",
        message1b: "<ul><li><h2>Find a tweet</h2></li><li><h2>Find a card</h2></li><li><h2>Reply with card</h2></li></ul>",
        message1c: "<ul><li><h2>Find a tweet</h2></li><li><h2>Find a card</h2></li><li><h2>Reply with card</h2></li></ul>",
        message1d: "<ul><li><h2>Find a tweet</h2></li><li><h2>Find a card</h2></li><li><h2>Reply with card</h2></li></ul>",
        message1e: "<ul><li><h2>Find a tweet</h2></li><li><h2>Find a card</h2></li><li><h2>Reply with card</h2></li></ul>",
        message2: "<h2>Gain eternal fame, spread bitcoin expertise</h2>",
        message3: "<h2>Step forward, spread bitcoin expertise</h2>",
        message4: "<h2>Get recognition, spread bitcoin expertise</h2>",
        message5: "<p>Play withthe configuration options to change the keywords, number of followers etc.</p>",
        message6: "<p>Depending on your search configurations it can take a while before real time tweets show.</p>",
        // message7: "<p>Play withthe configuration options to change the keywords, number of followers etc.</p>"
        message7: "All tweets with ‘bitcoin’ in it will show here.",
        message8: "Mostly relevant tweets about bitcoin will show here."
    },
    anyOfTheseStrings: "bitcoin will never, bitcoin can never, bitcoin just is not, bitcoin is one big, criminals, slow, laundering, energy, complicated, unfair, quantum, tax evaders, unsustainable, intrinsic value, shut down, scammers, roulette, only 21, not safe, black market, terrorists, tulip, greater fool, not scalable, anarchists, distribution unfair, hacked, anonymous, unsustainable, useless, ponzi, no backing, will die, forbidden, shut down, scammers, not gdpr, price down, terrorists, privacy breach, volatile, useless, deflation, chinese",
    noneOfTheseStrings: "I've hacked your computer,play online casino,Airdrop,All you have to do is RT,I will give one random follower,I will give someone",
    footerContent: "<small><img style='width: 20px;height: 20px; margin-right: 15px;' src='https://blockchainbird.org/t/media/img/logo/cc_icon_white_x2.png' alt='Two C's next to each other'><img style='width: 20px;height: 20px; margin-right: 15px;' src='https://blockchainbird.org/t/media/img/logo/attribution_icon_white_x2.png' alt='A symbol of a person'>Except where otherwise noted, content on this site is licensed under a <a target='_blank' rel='noopener' class='light' href='https://creativecommons.org/licenses/by/4.0/'>Creative Commons Attribution 4.0 International license</a>.</small>"

};